# Generated by Django 6.1.2 on 2026-10-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "niche",
                    models.CharField(
                        help_text="e.g. B2B SaaS, Health & Fitness", max_length=255
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(
                        help_text="Detailed description of the ideal customer"
                    ),
                ),
                (
                    "tone_of_voice",
                    models.CharField(
                        default="Engaging, authoritative, approachable",
                        help_text="e.g. Direct, conversational, witty, professional",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="e.g. @acme or linkedin.com/in/acme", max_length=255
                    ),
                ),
                ("profile_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="core.brandprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                ("post_url", models.URLField(blank=True, null=True)),
                (
                    "hook_text",
                    models.TextField(
                        help_text="The first 2-3 lines or main hook of the post/video"
                    ),
                ),
                (
                    "full_content",
                    models.TextField(
                        blank=True, help_text="Full caption or transcript", null=True
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                (
                    "outlier_score",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplication factor vs median (e.g. 3.2x)",
                    ),
                ),
                (
                    "is_outlier",
                    models.BooleanField(
                        default=False, help_text="True if outlier_score >= 2.5"
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=True, help_text="True if entered manually by user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.brandprofile",
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.competitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("hook", models.TextField(help_text="Suggested hook line")),
                (
                    "body_content",
                    models.TextField(
                        help_text="Full script, carousel breakdown, or post body"
                    ),
                ),
                (
                    "why_it_works",
                    models.TextField(
                        blank=True,
                        help_text="AI rationale for the viral hook",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="core.brandprofile",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_ideas",
                        to="core.socialpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
